In [1]:
import pandas as pd
import os

# Importando as bases

fiz outra query (deu 117k linhas) e não dropei nada, para não perder informação de ID. Meu objetivo é tentar traçar alguma relação entre o Kaggle e o AWS

In [2]:
kaggle=pd.read_csv("../Data/csv_Kaggle.csv")

In [3]:
customer=pd.read_csv("../Data/customers.csv")
order_items=pd.read_csv("../Data/order_items.csv")
products=pd.read_csv("../Data/products.csv")
sellers=pd.read_csv("../Data/sellers.csv")

In [4]:
customer.drop_duplicates(inplace=True)
order_items.drop_duplicates(inplace=True)
products.drop_duplicates(inplace=True)

In [5]:
display(kaggle)

,order_id,customer_id,order_purchase_timestamp,order_approved_at
0,cee3292f46ede6ea1dfabfcb200fcf47,0f8feee05f830b2be5955cf674a7d8f1,6/21/2018 15:00,6/21/2018 17:18
1,50dca53ca33b739bef09e7933e8b380e,d0580aed7f303a707d93b00b84c591a7,7/14/2018 09:47,7/14/2018 10:04
2,8087ec71e393d4dc6fc48041fe63cd51,b8dfb418e6cad762b91febf827d4b2e5,5/14/2018 10:03,5/14/2018 10:15
3,e6b6557ce111de79b31cc857f20ba212,90c8fe0d707ea62be3fcb5abd7bc784f,5/22/2018 18:41,5/22/2018 18:57
4,0b09c5e4c2512f627190ac55a78c35a3,6ba83000cf8c24413916a7a72fcb5173,4/30/2018 19:31,5/3/2018 04:12
...,...,...,...,...
28147,81cedc4d2132eb6f512354166e51b187,a8f6bb35d78515a1762eb626d52b6352,7/30/2018 21:02,7/30/2018 21:10
28148,95811675a89b66659996da5285a021db,5885969ba920706beb8d5381a2ba981c,8/9/2018 11:07,8/9/2018 15:25
28149,25bd2ad9d282f59e4e6a048ef9bf214f,be34bf56044c5614fc66d97251c0adc6,3/12/2018 16:20,3/12/2018 17:09
28150,9f9ac312604229686c04260955495c70,3357c4c3ecf82709236158cb2ac0ce9b,5/24/2018 11:38,5/24/2018 11:53
28151,f51c9940410ef77422e4efbca407c161,ceeaae7ee13b40a086d0140281bef2ac,8/16/2018 11:05,8/17/2018 03:30

In [6]:
#display(order_items)

In [7]:
#display(customer)

In [8]:
customer.drop("customer_unique_id",inplace=True,axis=1)

In [9]:
#display(order_items)

In [10]:
order_items.drop("order_item_id",axis=1, inplace=True)

In [11]:
#display(products)

In [12]:
products.drop(["product_name_lenght","product_description_lenght","product_photos_qty"],inplace=True,axis=1)

## Enriquecendo a base do Kaggle

In [13]:
order_items.drop_duplicates(subset="order_id",inplace=True)
order_items["order_id"].value_counts()

order_id
00010242fe8c5a6d1ba2dd792cb16214    1
ab13cb6c13063f2603a94c9ddca34f66    1
ab3a669dbdc7a8d447bb6fc7a158cf94    1
ab3a6663f21c1a36401300460d3c41cd    1
ab3a0535e202529923e53dfdadf8042e    1
                                   ..
5561adcb0fd46da4cad3048fa4e7fc00    1
555e60e282181725debc9eb2d69fda3f    1
555e4d40fb6beea866d46eb6a5a01b41    1
555e1afa0cf180760b7ea9f6d8ebc329    1
fffe41c64501cc87c801fd61db3f6244    1
Name: count, Length: 98666, dtype: int64

In [14]:
order_items.drop_duplicates(subset="order_id",inplace=True)
df=kaggle.merge(order_items,how="left",on="order_id")
display(df)

,order_id,customer_id,order_purchase_timestamp,order_approved_at,product_id,seller_id,shipping_limit_date,price,freight_value
0,cee3292f46ede6ea1dfabfcb200fcf47,0f8feee05f830b2be5955cf674a7d8f1,6/21/2018 15:00,6/21/2018 17:18,1bfb290d7273a442c874dbe74b4abae6,7c67e1448b00f6e969d365cea6b010ab,2018-07-05 17:18:41.000,69.99,23.20
1,50dca53ca33b739bef09e7933e8b380e,d0580aed7f303a707d93b00b84c591a7,7/14/2018 09:47,7/14/2018 10:04,eb048e296b8db6cd64b1bafd9500786c,1900267e848ceeba8fa32d80c1a5f5a8,2018-07-17 10:04:14.000,19.90,12.80
2,8087ec71e393d4dc6fc48041fe63cd51,b8dfb418e6cad762b91febf827d4b2e5,5/14/2018 10:03,5/14/2018 10:15,39cdb64dad488a6037d828d1cd514255,8f119a0aee85c0c8fc534629734e94fd,2018-05-18 10:15:20.000,22.50,8.64
3,e6b6557ce111de79b31cc857f20ba212,90c8fe0d707ea62be3fcb5abd7bc784f,5/22/2018 18:41,5/22/2018 18:57,803f77475e1b51b47f1bfec4f2ec353f,c9c7905cffc4ef9ff9f113554423e671,2018-05-25 18:57:37.000,69.99,15.37
4,0b09c5e4c2512f627190ac55a78c35a3,6ba83000cf8c24413916a7a72fcb5173,4/30/2018 19:31,5/3/2018 04:12,89321f94e35fc6d7903d36f74e351d40,16090f2ca825584b5a147ab24aa30c86,2018-05-09 04:12:51.000,27.90,18.23
...,...,...,...,...,...,...,...,...,...
28147,81cedc4d2132eb6f512354166e51b187,a8f6bb35d78515a1762eb626d52b6352,7/30/2018 21:02,7/30/2018 21:10,0d0bc6cf9765ffe8b4d3103138c96cdd,179d859f51292aac5c10806a356f7af9,2018-08-05 21:10:20.000,17.49,12.79
28148,95811675a89b66659996da5285a021db,5885969ba920706beb8d5381a2ba981c,8/9/2018 11:07,8/9/2018 15:25,aca2eb7d00ea1a7b8ebd4e68314663af,955fee9216a65b617aa5c0531780ce60,2018-08-13 15:25:22.000,109.90,22.07
28149,25bd2ad9d282f59e4e6a048ef9bf214f,be34bf56044c5614fc66d97251c0adc6,3/12/2018 16:20,3/12/2018 17:09,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-03-16 17:09:53.000,53.90,42.44
28150,9f9ac312604229686c04260955495c70,3357c4c3ecf82709236158cb2ac0ce9b,5/24/2018 11:38,5/24/2018 11:53,bb50f2e236e5eea0100680137654686c,f7ba60f8c3f99e7ee4042fdef03b70c4,2018-05-28 11:53:34.000,330.00,10.07
28151,f51c9940410ef77422e4efbca407c161,ceeaae7ee13b40a086d0140281bef2ac,8/16/2018 11:05,8/17/2018 03:30,020a80cb704bf65f38761fcedf2af192,ef2fbc2b607d8492bcffe657a4645434,2018-08-22 03:30:17.000,49.90,19.54

In [15]:
df=df.merge(customer, how="left", on="customer_id")
display(df)

,order_id,customer_id,order_purchase_timestamp,order_approved_at,product_id,seller_id,shipping_limit_date,price,freight_value,customer_zip_code_prefix,customer_city,customer_state
0,cee3292f46ede6ea1dfabfcb200fcf47,0f8feee05f830b2be5955cf674a7d8f1,6/21/2018 15:00,6/21/2018 17:18,1bfb290d7273a442c874dbe74b4abae6,7c67e1448b00f6e969d365cea6b010ab,2018-07-05 17:18:41.000,69.99,23.20,8280,NaN,NaN
1,50dca53ca33b739bef09e7933e8b380e,d0580aed7f303a707d93b00b84c591a7,7/14/2018 09:47,7/14/2018 10:04,eb048e296b8db6cd64b1bafd9500786c,1900267e848ceeba8fa32d80c1a5f5a8,2018-07-17 10:04:14.000,19.90,12.80,7151,guarulhos,sao paulo
2,8087ec71e393d4dc6fc48041fe63cd51,b8dfb418e6cad762b91febf827d4b2e5,5/14/2018 10:03,5/14/2018 10:15,39cdb64dad488a6037d828d1cd514255,8f119a0aee85c0c8fc534629734e94fd,2018-05-18 10:15:20.000,22.50,8.64,4013,SAO PAULO,SP
3,e6b6557ce111de79b31cc857f20ba212,90c8fe0d707ea62be3fcb5abd7bc784f,5/22/2018 18:41,5/22/2018 18:57,803f77475e1b51b47f1bfec4f2ec353f,c9c7905cffc4ef9ff9f113554423e671,2018-05-25 18:57:37.000,69.99,15.37,30660,belo horizonte,MG
4,0b09c5e4c2512f627190ac55a78c35a3,6ba83000cf8c24413916a7a72fcb5173,4/30/2018 19:31,5/3/2018 04:12,89321f94e35fc6d7903d36f74e351d40,16090f2ca825584b5a147ab24aa30c86,2018-05-09 04:12:51.000,27.90,18.23,89056,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
28147,81cedc4d2132eb6f512354166e51b187,a8f6bb35d78515a1762eb626d52b6352,7/30/2018 21:02,7/30/2018 21:10,0d0bc6cf9765ffe8b4d3103138c96cdd,179d859f51292aac5c10806a356f7af9,2018-08-05 21:10:20.000,17.49,12.79,12705,cruzeiro,NaN
28148,95811675a89b66659996da5285a021db,5885969ba920706beb8d5381a2ba981c,8/9/2018 11:07,8/9/2018 15:25,aca2eb7d00ea1a7b8ebd4e68314663af,955fee9216a65b617aa5c0531780ce60,2018-08-13 15:25:22.000,109.90,22.07,72002,NaN,NaN
28149,25bd2ad9d282f59e4e6a048ef9bf214f,be34bf56044c5614fc66d97251c0adc6,3/12/2018 16:20,3/12/2018 17:09,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-03-16 17:09:53.000,53.90,42.44,66610,belem,PA
28150,9f9ac312604229686c04260955495c70,3357c4c3ecf82709236158cb2ac0ce9b,5/24/2018 11:38,5/24/2018 11:53,bb50f2e236e5eea0100680137654686c,f7ba60f8c3f99e7ee4042fdef03b70c4,2018-05-28 11:53:34.000,330.00,10.07,3315,NaN,NaN
28151,f51c9940410ef77422e4efbca407c161,ceeaae7ee13b40a086d0140281bef2ac,8/16/2018 11:05,8/17/2018 03:30,020a80cb704bf65f38761fcedf2af192,ef2fbc2b607d8492bcffe657a4645434,2018-08-22 03:30:17.000,49.90,19.54,85301,laranjeiras do sul,NaN

In [16]:
df=df.merge(products,how="left",on="product_id")

In [17]:
df

,order_id,customer_id,order_purchase_timestamp,order_approved_at,product_id,seller_id,shipping_limit_date,price,freight_value,customer_zip_code_prefix,customer_city,customer_state,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,cee3292f46ede6ea1dfabfcb200fcf47,0f8feee05f830b2be5955cf674a7d8f1,6/21/2018 15:00,6/21/2018 17:18,1bfb290d7273a442c874dbe74b4abae6,7c67e1448b00f6e969d365cea6b010ab,2018-07-05 17:18:41.000,69.99,23.20,8280,NaN,NaN,moveis_escritorio,10075.0,55.0,64.0,26.0
1,50dca53ca33b739bef09e7933e8b380e,d0580aed7f303a707d93b00b84c591a7,7/14/2018 09:47,7/14/2018 10:04,eb048e296b8db6cd64b1bafd9500786c,1900267e848ceeba8fa32d80c1a5f5a8,2018-07-17 10:04:14.000,19.90,12.80,7151,guarulhos,sao paulo,cama_mesa_banho,250.0,16.0,10.0,16.0
2,8087ec71e393d4dc6fc48041fe63cd51,b8dfb418e6cad762b91febf827d4b2e5,5/14/2018 10:03,5/14/2018 10:15,39cdb64dad488a6037d828d1cd514255,8f119a0aee85c0c8fc534629734e94fd,2018-05-18 10:15:20.000,22.50,8.64,4013,SAO PAULO,SP,casa_construcao,300.0,28.0,9.0,18.0
3,e6b6557ce111de79b31cc857f20ba212,90c8fe0d707ea62be3fcb5abd7bc784f,5/22/2018 18:41,5/22/2018 18:57,803f77475e1b51b47f1bfec4f2ec353f,c9c7905cffc4ef9ff9f113554423e671,2018-05-25 18:57:37.000,69.99,15.37,30660,belo horizonte,MG,automotivo,350.0,17.0,6.0,20.0
4,0b09c5e4c2512f627190ac55a78c35a3,6ba83000cf8c24413916a7a72fcb5173,4/30/2018 19:31,5/3/2018 04:12,89321f94e35fc6d7903d36f74e351d40,16090f2ca825584b5a147ab24aa30c86,2018-05-09 04:12:51.000,27.90,18.23,89056,NaN,NaN,alimentos,150.0,17.0,13.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28147,81cedc4d2132eb6f512354166e51b187,a8f6bb35d78515a1762eb626d52b6352,7/30/2018 21:02,7/30/2018 21:10,0d0bc6cf9765ffe8b4d3103138c96cdd,179d859f51292aac5c10806a356f7af9,2018-08-05 21:10:20.000,17.49,12.79,12705,cruzeiro,NaN,eletronicos,200.0,19.0,13.0,17.0
28148,95811675a89b66659996da5285a021db,5885969ba920706beb8d5381a2ba981c,8/9/2018 11:07,8/9/2018 15:25,aca2eb7d00ea1a7b8ebd4e68314663af,955fee9216a65b617aa5c0531780ce60,2018-08-13 15:25:22.000,109.90,22.07,72002,NaN,NaN,moveis_decoracao,2600.0,50.0,10.0,30.0
28149,25bd2ad9d282f59e4e6a048ef9bf214f,be34bf56044c5614fc66d97251c0adc6,3/12/2018 16:20,3/12/2018 17:09,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-03-16 17:09:53.000,53.90,42.44,66610,belem,PA,ferramentas_jardim,1650.0,30.0,22.0,30.0
28150,9f9ac312604229686c04260955495c70,3357c4c3ecf82709236158cb2ac0ce9b,5/24/2018 11:38,5/24/2018 11:53,bb50f2e236e5eea0100680137654686c,f7ba60f8c3f99e7ee4042fdef03b70c4,2018-05-28 11:53:34.000,330.00,10.07,3315,NaN,NaN,beleza_saude,400.0,34.0,4.0,22.0
28151,f51c9940410ef77422e4efbca407c161,ceeaae7ee13b40a086d0140281bef2ac,8/16/2018 11:05,8/17/2018 03:30,020a80cb704bf65f38761fcedf2af192,ef2fbc2b607d8492bcffe657a4645434,2018-08-22 03:30:17.000,49.90,19.54,85301,laranjeiras do sul,NaN,automotivo,800.0,26.0,9.0,24.0

In [18]:
df=df.merge(sellers,how="left",on="seller_id")
df

,order_id,customer_id,order_purchase_timestamp,order_approved_at,product_id,seller_id,shipping_limit_date,price,freight_value,customer_zip_code_prefix,customer_city,customer_state,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,cee3292f46ede6ea1dfabfcb200fcf47,0f8feee05f830b2be5955cf674a7d8f1,6/21/2018 15:00,6/21/2018 17:18,1bfb290d7273a442c874dbe74b4abae6,7c67e1448b00f6e969d365cea6b010ab,2018-07-05 17:18:41.000,69.99,23.20,8280,NaN,NaN,moveis_escritorio,10075.0,55.0,64.0,26.0,8577,itaquaquecetuba,SP
1,50dca53ca33b739bef09e7933e8b380e,d0580aed7f303a707d93b00b84c591a7,7/14/2018 09:47,7/14/2018 10:04,eb048e296b8db6cd64b1bafd9500786c,1900267e848ceeba8fa32d80c1a5f5a8,2018-07-17 10:04:14.000,19.90,12.80,7151,guarulhos,sao paulo,cama_mesa_banho,250.0,16.0,10.0,16.0,14940,ibitinga,SP
2,8087ec71e393d4dc6fc48041fe63cd51,b8dfb418e6cad762b91febf827d4b2e5,5/14/2018 10:03,5/14/2018 10:15,39cdb64dad488a6037d828d1cd514255,8f119a0aee85c0c8fc534629734e94fd,2018-05-18 10:15:20.000,22.50,8.64,4013,SAO PAULO,SP,casa_construcao,300.0,28.0,9.0,18.0,6440,barueri,SP
3,e6b6557ce111de79b31cc857f20ba212,90c8fe0d707ea62be3fcb5abd7bc784f,5/22/2018 18:41,5/22/2018 18:57,803f77475e1b51b47f1bfec4f2ec353f,c9c7905cffc4ef9ff9f113554423e671,2018-05-25 18:57:37.000,69.99,15.37,30660,belo horizonte,MG,automotivo,350.0,17.0,6.0,20.0,6871,itapecerica da serra,SP
4,0b09c5e4c2512f627190ac55a78c35a3,6ba83000cf8c24413916a7a72fcb5173,4/30/2018 19:31,5/3/2018 04:12,89321f94e35fc6d7903d36f74e351d40,16090f2ca825584b5a147ab24aa30c86,2018-05-09 04:12:51.000,27.90,18.23,89056,NaN,NaN,alimentos,150.0,17.0,13.0,13.0,12940,atibaia,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28147,81cedc4d2132eb6f512354166e51b187,a8f6bb35d78515a1762eb626d52b6352,7/30/2018 21:02,7/30/2018 21:10,0d0bc6cf9765ffe8b4d3103138c96cdd,179d859f51292aac5c10806a356f7af9,2018-08-05 21:10:20.000,17.49,12.79,12705,cruzeiro,NaN,eletronicos,200.0,19.0,13.0,17.0,9411,ribeirao pires,SP
28148,95811675a89b66659996da5285a021db,5885969ba920706beb8d5381a2ba981c,8/9/2018 11:07,8/9/2018 15:25,aca2eb7d00ea1a7b8ebd4e68314663af,955fee9216a65b617aa5c0531780ce60,2018-08-13 15:25:22.000,109.90,22.07,72002,NaN,NaN,moveis_decoracao,2600.0,50.0,10.0,30.0,4782,sao paulo,SP
28149,25bd2ad9d282f59e4e6a048ef9bf214f,be34bf56044c5614fc66d97251c0adc6,3/12/2018 16:20,3/12/2018 17:09,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-03-16 17:09:53.000,53.90,42.44,66610,belem,PA,ferramentas_jardim,1650.0,30.0,22.0,30.0,15025,sao jose do rio preto,SP
28150,9f9ac312604229686c04260955495c70,3357c4c3ecf82709236158cb2ac0ce9b,5/24/2018 11:38,5/24/2018 11:53,bb50f2e236e5eea0100680137654686c,f7ba60f8c3f99e7ee4042fdef03b70c4,2018-05-28 11:53:34.000,330.00,10.07,3315,NaN,NaN,beleza_saude,400.0,34.0,4.0,22.0,9628,sao bernardo do campo,SP
28151,f51c9940410ef77422e4efbca407c161,ceeaae7ee13b40a086d0140281bef2ac,8/16/2018 11:05,8/17/2018 03:30,020a80cb704bf65f38761fcedf2af192,ef2fbc2b607d8492bcffe657a4645434,2018-08-22 03:30:17.000,49.90,19.54,85301,laranjeiras do sul,NaN,automotivo,800.0,26.0,9.0,24.0,20051,rio de janeiro,RJ

In [19]:
df.isnull().sum()

order_id                        0
customer_id                     0
order_purchase_timestamp        0
order_approved_at               0
product_id                      0
seller_id                       0
shipping_limit_date             0
price                         263
freight_value                 274
customer_zip_code_prefix        0
customer_city                9909
customer_state              14146
product_category_name         140
product_weight_g                0
product_length_cm               0
product_height_cm               0
product_width_cm                0
seller_zip_code_prefix          0
seller_city                     0
seller_state                    0
dtype: int64

In [20]:
caminho_arquivo = os.path.join("../Data", 'Kaggle_enriquecido.csv')

# Salve o DataFrame em um arquivo CSV na pasta Data
df.to_csv(caminho_arquivo, index=False)